name: Automation test

on:
  workflow_dispatch:
    branches: [master]
    inputs:
      test_type:
        description: 'Please input test type.'
        type: choice
        required: true
        default: 'e2e'
        options:
          - e2e
          - integration
      test_environment:
        description: 'Please input environment to test.'
        type: choice
        required: true
        default: 'SIT'
        options:
          - SIT
          - UAT
      githost_environment:
        description: 'Please input git host environment to run the test (use legacy when vpn is required).'
        type: choice
        required: true
        default: 'ubuntu-latest'
        options:
          - ubuntu-22-4core
          - legacy
      squad:
        description: 'Please input squad. Example: spvcockpit, are, agenttools, dms, ndf4w, ndf2w, operation, sharia, etc'
        required: true
        default: ''

jobs:
  # FormatingStandart:
  #   name: Lint and Prettier check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Depedencies
  #       run: npm i

  RunTest:
    # needs: [FormatingStandart]
    uses: bfi-finance/cypress-test-automation/.github/workflows/reuseable.yml@research/github-action
    with:
      test_type: ${{ github.event.inputs.test_type }}
      test_environment: ${{ github.event.inputs.test_environment }}
      githost_environment: ${{ github.event.inputs.githost_environment }}
      squad: ${{ github.event.inputs.squad }}
    secrets: inherit
